### ISSUE TITLE
When you Drag the item to trash box it stays in the canvas

### ISSUE THREAD

**Issue by hosnyben** [keermanish/example-react-page-maker#4] opened 2020-01-03 00:57 UTC
When you Drag the item to trash box it stays in the canvas, and when you check the json you notice that initialElements stays te same

**Comment by keermanish** [comment] 2020-01-03 11:11
Hmm, I'm not able to reproduce this problem. I tried on below working example.

https://example-react-page-make.netlify.com/

check once and let me know.

**Comment by hosnyben** [comment] 2020-01-03 14:36
> Hmm, I'm not able to reproduce this problem. I tried on below working example.
> 
> https://example-react-page-make.netlify.com/
> 
> check once and let me know.

Hey Manish,
Please follow those steps to get the same issue.
1- Clear canvas
2- Add 3 by 3 Grid Layout
3- Add text field inside any sort of column of the grid layout
4- You will notice in the JSON the **initialElements** of grid element is filled with the textfield element
5- Try to remove the text field (By clocking on the trash icon or by draggin the element to trashbox)
6- You will notice in the JSON the **initialElements** of grid element stays filled with the textfield element, event if the textfield element is removed

**Comment by hosnyben** [comment] 2020-01-03 15:01
And why we use "child" and "initialElements" if it does the same functionnalities ?

**Comment by keermanish** [comment] 2020-03-22 08:43
Sorry for the super late response.

here are the steps I tried and still not able to reproduce the problem.
https://youtu.be/pkE8CMeUxAs

also, there is a reason behind why initialElements and child props are in sync, basically, it helps to find out whether parent element (dropdoze) is done with initial rendering(hydration) process ([check here](https://github.com/keermanish/react-page-maker/blob/master/src/components/Dropzone/Dropzone.js#L339)), I know this is not the best way to do it (as this behavior was necessary for hydration process only). I will try to optimize this bit in a future release.

**Comment by keermanish** [comment] 2020-03-22 08:43
Closing this out. Let me know if you still having an issue.

**Closed as completed by keermanish** 2020-03-22 08:43 UTC
